export enum CONTROL_BLOCK {
  SET_COLUMNS = 'CONTROL_BLOCK.SET_COLUMNS',
  SET_LINES = 'CONTROL_BLOCK.SET_LINES',
  SET_STEPS = 'CONTROL_BLOCK.SET_STEPS',
  START_GAME = 'CONTROL_BLOCK.START_GAME',
}
